# -*- coding: utf-8 -*-
"""scrapping images.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zyuKtgoyTOJfhPFTSvBC9VESr8R0DYlE
"""

# install bing image downloader
# memakai bing images, bukan dari google images
!pip install bing-image-downloader

# buat direktori untuk menyimpan dataset
!mkdir gambar_wisata_Pekanbaru

from bing_image_downloader import downloader
downloader.download('Kawah Putih Pekanbaru', limit = 15,
                    output_dir = 'gambar_wisata_Pekanbaru',
                    adult_filter_off = True)

downloader.download('Rainbow Hills Rumbai Pekanbaru', limit = 15,
                    output_dir = 'gambar_wisata_Pekanbaru',
                    adult_filter_off = True)

downloader.download('Riau Fantasi Pekanbaru', limit = 15,
                    output_dir = 'gambar_wisata_Pekanbaru',
                    adult_filter_off = True)

downloader.download('Alam Mayang Pekanbaru', limit = 15,
                    output_dir = 'gambar_wisata_Pekanbaru',
                    adult_filter_off = True)

downloader.download('Bukit Kapus Air Hitam Pekanbaru', limit = 15,
                    output_dir = 'gambar_wisata_Pekanbaru',
                    adult_filter_off = True)

downloader.download('Kebun Binatang Kasang Kulim Pekanbaru', limit = 15,
                    output_dir = 'gambar_wisata_Pekanbaru',
                    adult_filter_off = True)

downloader.download('Arboretum UNRI Pekanbaru', limit = 15,
                    output_dir = 'gambar_wisata_Pekanbaru',
                    adult_filter_off = True)

downloader.download('Hutan Kota Pekanbaru', limit = 15,
                    output_dir = 'gambar_wisata_Pekanbaru',
                    adult_filter_off = True)

downloader.download('Danau Lembah Sari Pekanbaru', limit = 15,
                    output_dir = 'gambar_wisata_Pekanbaru',
                    adult_filter_off = True)

downloader.download('Istana Siak Sri Indrapura Pekanbaru', limit = 15,
                    output_dir = 'gambar_wisata_Pekanbaru',
                    adult_filter_off = True)

downloader.download('Danau Bandar Kayangan Pekanbaru', limit = 15,
                    output_dir = 'gambar_wisata_Pekanbaru',
                    adult_filter_off = True)

downloader.download('Desa Wisata Okura Pekanbaru', limit = 15,
                    output_dir = 'gambar_wisata_Pekanbaru',
                    adult_filter_off = True)

downloader.download('Masjid Agung An-Nur Pekanbaru', limit = 15,
                    output_dir = 'gambar_wisata_Pekanbaru',
                    adult_filter_off = True)

downloader.download('Anjungan Seni Idrus Tintin Pekanbaru', limit = 15,
                    output_dir = 'gambar_wisata_Pekanbaru',
                    adult_filter_off = True)

downloader.download('Perpustakaan Soerman H.S Pekanbaru', limit = 15,
                    output_dir = 'gambar_wisata_Pekanbaru',
                    adult_filter_off = True)

downloader.download('Masjid Senapelan Pekanbaru', limit = 15,
                    output_dir = 'gambar_wisata_Pekanbaru',
                    adult_filter_off = True)

downloader.download('Museum Sang Nila Utama Pekanbaru', limit = 15,
                    output_dir = 'gambar_wisata_Pekanbaru',
                    adult_filter_off = True)

downloader.download('Bono Sungai Kampar Pekanbaru', limit = 15,
                    output_dir = 'gambar_wisata_Pekanbaru',
                    adult_filter_off = True)

downloader.download('Air Terjun Aek Martua Pekanbaru', limit = 15,
                    output_dir = 'gambar_wisata_Pekanbaru',
                    adult_filter_off = True)

downloader.download('Pasar Bawah Pekanbaru', limit = 15,
                    output_dir = 'gambar_wisata_Pekanbaru',
                    adult_filter_off = True)

downloader.download('Citraland Waterpark Pekanbaru', limit = 15,
                    output_dir = 'gambar_wisata_Pekanbaru',
                    adult_filter_off = True)

downloader.download('Air Terjun Batu Dinding Pekanbaru', limit = 15,
                    output_dir = 'gambar_wisata_Pekanbaru',
                    adult_filter_off = True)

downloader.download('Sup Tunjang Tribuana Pekanbaru', limit = 15,
                    output_dir = 'gambar_wisata_Pekanbaru',
                    adult_filter_off = True)

downloader.download('Air Terjun Guruh Gemurai Pekanbaru', limit = 15,
                    output_dir = 'gambar_wisata_Pekanbaru',
                    adult_filter_off = True)

downloader.download('Teluk Jering Pekanbaru', limit = 15,
                    output_dir = 'gambar_wisata_Pekanbaru',
                    adult_filter_off = True)

downloader.download('Candi Muara Takus Pekanbaru', limit = 15,
                    output_dir = 'gambar_wisata_Pekanbaru',
                    adult_filter_off = True)

downloader.download('Air Terjun Batang Kapas Pekanbaru', limit = 15,
                    output_dir = 'gambar_wisata_Pekanbaru',
                    adult_filter_off = True)

downloader.download('Taman Hutan Raya Sultan Syarif Kasim Pekanbaru', limit = 15,
                    output_dir = 'gambar_wisata_Pekanbaru',
                    adult_filter_off = True)

downloader.download('Asia Heritage Pekanbaru', limit = 15,
                    output_dir = 'gambar_wisata_Pekanbaru',
                    adult_filter_off = True)

import numpy as np
import matplotlib.pyplot as plt
import os
import cv2
from tqdm import tqdm

DATADIR = "/content/gambar_wisata_Pekanbaru/"

DESTINATION = ['Kawah Putih Pekanbaru',
              'Rainbow Hills Rumbai Pekanbaru',
              'Riau Fantasi Pekanbaru',
              'Alam Mayang Pekanbaru',
              'Bukit Kapus Air Hitam Pekanbaru',
              'Kebun Binatang Kasang Kulim Pekanbaru',
              'Arboretum UNRI Pekanbaru',
              'Hutan Kota Pekanbaru',
              'Danau Lembah Sari Pekanbaru',
              'Istana Siak Sri Indrapura Pekanbaru',
              'Danau Bandar Kayangan Pekanbaru',
              'Desa Wisata Okura Pekanbaru',
              'Masjid Agung An-Nur Pekanbaru',
              'Anjungan Seni Idrus Tintin Pekanbaru',
              'Perpustakaan Soerman H.S Pekanbaru',
              'Masjid Senapelan Pekanbaru',
              'Museum Sang Nila Utama Pekanbaru',
              'Bono Sungai Kampar Pekanbaru',
              'Air Terjun Aek Martua Pekanbaru',
              'Pasar Bawah Pekanbaru',
              'Citraland Waterpark Pekanbaru',
              'Air Terjun Batu Dinding Pekanbaru',
              'Sup Tunjang Tribuana Pekanbaru',
              'Air Terjun Guruh Gemurai Pekanbaru',
              'Teluk Jering Pekanbaru',
              'Candi Muara Takus Pekanbaru',
              'Air Terjun Batang Kapas Pekanbaru',
              'Taman Hutan Raya Sultan Syarif Kasim Pekanbaru',
              'Asia Heritage Pekanbaru',]

for i in DESTINATION:  
    path = os.path.join(DATADIR, i)
    for image in os.listdir(path):
        image_array = cv2.imread(os.path.join(path,image) ,cv2.IMREAD_GRAYSCALE)
        plt.imshow(image_array, cmap='gray')
        plt.show()

        break
    break

print(image_array)

print(image_array.shape)

IMAGE_SIZE = 100

new_array = cv2.resize(image_array, (IMAGE_SIZE, IMAGE_SIZE))
plt.imshow(new_array, cmap='gray')
plt.show()

training_data = []

def create_training_data():
    for i in DESTINATION: 

        path = os.path.join(DATADIR,i)  
        class_num = DESTINATION.index(i)  

        for image in tqdm(os.listdir(path)): 
            try:
                image_array = cv2.imread(os.path.join(path,image) ,cv2.IMREAD_GRAYSCALE) 
                new_array = cv2.resize(image_array, (IMAGE_SIZE, IMAGE_SIZE))  
                training_data.append([new_array, class_num])  
            except Exception as e:  
                pass

create_training_data()

print(len(training_data))

import random

random.shuffle(training_data)

for sample in training_data[:10]:
    print(sample[1])

X = []
y = []

for features,label in training_data:
    X.append(features)
    y.append(label)

print(X[0].reshape(-1, IMAGE_SIZE, IMAGE_SIZE, 1))

X = np.array(X).reshape(-1, IMAGE_SIZE, IMAGE_SIZE, 1)

import pickle

pickle_out = open("X.pickle","wb")
pickle.dump(X, pickle_out)
pickle_out.close()

pickle_out = open("y.pickle","wb")
pickle.dump(y, pickle_out)
pickle_out.close()

pickle_in = open("X.pickle","rb")
X = pickle.load(pickle_in)

pickle_in = open("y.pickle","rb")
y = pickle.load(pickle_in)